SCENARIO_ID = "ops-core-voyages-v1"


INCIDENT_TEMPLATES = [
    {
        "type": "Engine Failure",
        "severity": "High",
        "description": "Main engine output is reduced while engineers inspect the issue.",
        "operationalImpact": "Reduced propulsion capacity and increased ETA risk.",
        "speedMultiplier": 0.35,
        "speedReductionPct": 65,
    },
    {
        "type": "Fire",
        "severity": "Critical",
        "description": "Fire response procedure active. Vessel is holding reduced speed.",
        "operationalImpact": "Emergency response active with crew safety as the primary priority.",
        "speedMultiplier": 0.15,
        "speedReductionPct": 85,
    },
    {
        "type": "Fuel Leak",
        "severity": "Medium",
        "description": "Fuel system alarm active. Vessel is proceeding under caution.",
        "operationalImpact": "Fuel margin and environmental exposure require close monitoring.",
        "speedMultiplier": 0.65,
        "speedReductionPct": 35,
    },
    {
        "type": "Weather Delay",
        "severity": "Low",
        "description": "Heavy weather along the route is slowing vessel progress.",
        "operationalImpact": "Route remains viable, but schedule confidence is reduced.",
        "speedMultiplier": 0.55,
        "speedReductionPct": 45,
    },
    {
        "type": "Port Congestion",
        "severity": "Medium",
        "description": "Destination berth availability has shifted into a congestion watch.",
        "operationalImpact": "Arrival plan may require speed adjustment or revised berth coordination.",
        "speedMultiplier": 0.82,
        "speedReductionPct": 18,
    },
    {
        "type": "Navigation Warning",
        "severity": "High",
        "description": "Route watch active due to traffic separation and local navigation warnings.",
        "operationalImpact": "Bridge team should review waypoints and maintain tighter route monitoring.",
        "speedMultiplier": 0.72,
        "speedReductionPct": 28,
    },
]


SCENARIO_EVENTS = [
    {"tick": 2, "action": "open", "voyageId": "voyage_001", "incidentType": "Engine Failure"},
    {"tick": 4, "action": "resolve", "voyageId": "voyage_003"},
    {"tick": 6, "action": "open", "voyageId": "voyage_002", "incidentType": "Fuel Leak"},
    {"tick": 9, "action": "resolve", "voyageId": "voyage_001"},
    {"tick": 11, "action": "open", "voyageId": "voyage_003", "incidentType": "Navigation Warning"},
    {"tick": 14, "action": "resolve", "voyageId": "voyage_002"},
]


VOYAGE_SEEDS = [
    {
        "id": "voyage_001",
        "ship": {
            "id": "ship_001",
            "name": "MT Oceanic Explorer",
            "type": "Tanker",
            "imo": "IMO 9387421",
            "flag": "Marshall Islands",
            "operator": "Oceanic Maritime",
        },
        "origin": {
            "name": "Boston",
            "country": "USA",
            "unLocode": "USBOS",
            "lat": 42.3601,
            "lng": -71.0589,
        },
        "destination": {
            "name": "Rotterdam",
            "country": "Netherlands",
            "unLocode": "NLRTM",
            "lat": 51.9244,
            "lng": 4.4777,
        },
        "route": [
            [42.3601, -71.0589],
            [43.1, -58.0],
            [45.0, -42.5],
            [49.2, -18.0],
            [51.9244, 4.4777],
        ],
        "speedKnots": 16.5,
        "progress": 0.32,
        "cargo": {"type": "Refined petroleum", "weightTons": 72000, "hazardClass": "Liquid bulk"},
        "fuelRemainingPct": 68,
        "weather": {
            "condition": "Moderate Atlantic swell",
            "waveHeightM": 3.2,
            "windSpeedKnots": 26,
            "visibilityNm": 8.5,
            "riskLevel": "Medium",
        },
        "destinationPort": {
            "berthName": "Maasvlakte Berth 4",
            "berthStatus": "On Schedule",
            "congestionLevel": "Medium",
            "arrivalWindowHours": [110, 122],
        },
    },
    {
        "id": "voyage_002",
        "ship": {
            "id": "ship_002",
            "name": "MV Sapphire Strait",
            "type": "Container Ship",
            "imo": "IMO 9738157",
            "flag": "Singapore",
            "operator": "Oceanic Maritime",
        },
        "origin": {
            "name": "Singapore",
            "country": "Singapore",
            "unLocode": "SGSIN",
            "lat": 1.3521,
            "lng": 103.8198,
        },
        "destination": {
            "name": "Dubai",
            "country": "UAE",
            "unLocode": "AEDXB",
            "lat": 25.2048,
            "lng": 55.2708,
        },
        "route": [
            [1.3521, 103.8198],
            [5.9, 94.5],
            [8.4, 78.6],
            [12.4, 63.5],
            [22.7, 59.1],
            [25.2048, 55.2708],
        ],
        "speedKnots": 18.0,
        "progress": 0.48,
        "cargo": {"type": "Mixed containers", "weightTons": 51000, "hazardClass": "General cargo"},
        "fuelRemainingPct": 74,
        "weather": {
            "condition": "Hot, clear visibility",
            "waveHeightM": 1.1,
            "windSpeedKnots": 12,
            "visibilityNm": 12.0,
            "riskLevel": "Low",
        },
        "destinationPort": {
            "berthName": "Jebel Ali Terminal 2",
            "berthStatus": "Watch",
            "congestionLevel": "Medium",
            "arrivalWindowHours": [70, 82],
        },
    },
    {
        "id": "voyage_003",
        "ship": {
            "id": "ship_003",
            "name": "MV Pacific Horizon",
            "type": "Bulk Carrier",
            "imo": "IMO 9442037",
            "flag": "Panama",
            "operator": "Oceanic Maritime",
        },
        "origin": {
            "name": "Shanghai",
            "country": "China",
            "unLocode": "CNSHA",
            "lat": 31.2304,
            "lng": 121.4737,
        },
        "destination": {
            "name": "Los Angeles",
            "country": "USA",
            "unLocode": "USLAX",
            "lat": 33.7405,
            "lng": -118.2775,
        },
        "route": [
            [31.2304, 121.4737],
            [34.0, 142.0],
            [38.5, 165.0],
            [42.0, -170.0],
            [38.2, -145.0],
            [33.7405, -118.2775],
        ],
        "speedKnots": 14.5,
        "progress": 0.58,
        "cargo": {"type": "Iron ore", "weightTons": 86000, "hazardClass": "Dry bulk"},
        "fuelRemainingPct": 57,
        "weather": {
            "condition": "North Pacific low-pressure system",
            "waveHeightM": 4.6,
            "windSpeedKnots": 34,
            "visibilityNm": 5.5,
            "riskLevel": "High",
        },
        "destinationPort": {
            "berthName": "Pier 400 Dry Bulk",
            "berthStatus": "On Schedule",
            "congestionLevel": "Low",
            "arrivalWindowHours": [118, 132],
        },
        "initialIncidentType": "Weather Delay",
    },
]
